#! /bin/bash
# ~/.local_aliases
# only local aliases goes here

# common alaias
alias myip='echo -en "Private IPs :\n\t"; ifconfig | grep inet | egrep -v "inet6|127.0.0.1" | cut -f2 -d" "; echo -en "Public IPs :\n\t"; dig +short myip.opendns.com @resolver1.opendns.com'
alias flushdns='sudo dscacheutil -flushcache;sudo killall -HUP mDNSResponder; say cache flushed'
alias passgen='gpg --gen-random --armor 1 15'

# Editors
alias vi='nvim'
alias vim='nvim'
alias em='emacs -nw --no-splash'
alias emacs='emacs -nw --no-splash'

# Tmux
alias show_tmux_colors='for i in {0..255}; do printf "\x1b[38;5;${i}mcolour${i}\x1b[0m\n"; done'

# git
alias gitgraph='git log --graph --oneline --decorate --all --source'

# Python
alias python='python'
alias pip='pip3'

# tmux
alias owork='tmux attach -t work'
alias ide='tmux attach -t ide'

# debugging
alias psstate='ps -axo pid,comm,stat --sort=-stat'
alias pst='ps auwfx'

# Docker
alias drm_notrunning="docker ps -a | grep Exited | awk '{print $1}' | xargs docker rm"

# K8
alias kc='kubectl'

# SSH Socks Tunnel
alias sshhttpstunnel='ssh -D 8123 -f -C -q -N remoteproxy'

# Remote VNC Tunnel
alias homevnctunnel='ssh -L 5900:localhost:5900 cmdcenter'

# Set defaults for some of the tools/commands
alias rsync='rsync -a --timeout 60 --stats --exclude=".DS_Store" --exclude=".idea/*.xml" --exclude=".idea/*.iml"  --exclude=".terraform" --exclude=".terragrunt-cache" --exclude=".terraform.lock.hcl"'

# Pull/Push code from/to work laptop
alias pull_code_from_wl='rsync --delete --delete-after ashok@wl:~/code/ ~/code/work/'
alias push_code_to_wl='rsync --delete --delete-after ~/code/work/ ashok@wl:~/code/'

# Pull/Push code from/to personal laptop
alias push_code_to_niffler='rsync --delete --delete-after ~/code/ ashokraja@niffler:~/code/'
alias pull_code_from_niffler='rsync --delete --delete-after ashokraja@niffler:~/code/ ~/code/'

#
alias edit=fleet
alias view=fleet
