#! /bin/bash
# ~/.local_aliases
# only local aliases goes here

# common alaias
alias myip='echo -en "Private IPs :\n\t"; ifconfig | grep inet | egrep -v "inet6|127.0.0.1" | cut -f2 -d" "; echo -en "Public IPs :\n\t"; dig +short myip.opendns.com @resolver1.opendns.com'
alias flushdns='sudo dscacheutil -flushcache;sudo killall -HUP mDNSResponder; say cache flushed'
alias passgen='gpg --gen-random --armor 1 15'

# Editors
alias vi='nvim'
alias vim='nvim'
alias em='emacs -nw --no-splash'
alias emacs='emacs -nw --no-splash'
alias fzf="fzf --height=40% --layout=reverse --info=inline --border --preview 'bat --style full --color always {}'"

# git
alias gitgraph='git log --graph --oneline --decorate --all --source'

# Python
alias python='python'
alias pip='pip3'

# tmux
alias owork='tmux attach -t work'
alias ide='tmux attach -t ide'

# debugging
alias psstate='ps -axo pid,comm,stat --sort=-stat'
alias pst='ps auwfx'

# Docker
alias drm_notrunning="docker ps -a | grep Exited | awk '{print $1}' | xargs docker rm"

# K8
alias kc='kubectl'

# SSH Socks Tunnel
alias sshhttpstunnel='ssh -D 8123 -f -C -q -N remoteproxy'

# Remote VNC Tunnel
alias homevnctunnel='ssh -L 5900:localhost:5900 cmdcenter'

# Pull/Push code from/to work laptop
alias wl_pull_code='rsync -av --exclude=".idea" --exclude=".vscode" --exclude=".terraform" --exclude=".terragrunt-cache" --exclude=".terraform.lock.hcl" --delete --delete-after --timeout 60 --stats ashok@wl:~/code/ ~/code/work/'
alias wl_push_code='rsync -av --exclude=".idea" --exclude=".vscode" --exclude=".terraform" --exclude=".terragrunt-cache" --exclude=".terraform.lock.hcl" --delete --delete-after --timeout 60 --stats ~/code/work/ ashok@wl:~/code/'

