#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Load zprofile if not already loaded to prevent duplicate initialization
if [[ -z "$ZPROFILE_LOADED" ]]; then
    [[ -f ~/.zprofile ]] && source ~/.zprofile
fi

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Powerlevel10k Customization
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
if [[ $TERM_PROGRAM == "WarpTerminal" ]]; then
    [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k-warp.zsh
    POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true
else
    [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
    POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true
fi

# Source Prezto.
[[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]] && source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"

# Customize to your needs...

# History
HISTFILE=$HOME/.zsh_history
HISTSIZE=10000000
SAVEHIST=10000000

setopt ALIAS_FUNC_DEF
# Alias definition
[[ -f "$HOME/.local_aliases" ]] && source "$HOME/.local_aliases"
[[ -f "$HOME/.shell_helper_functions.sh" ]] && source "$HOME/.shell_helper_functions.sh"
[[ -f "$HOME/.local_workspecalias" ]] && source "$HOME/.local_workspecalias"
[[ -f "$HOME/.user_env_pass" ]] && source "$HOME/.user_env_pass"

# LANG
export LC_ALL=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LANG=en_US.UTF-8

# Auto load some default completions
autoload -U +X compinit && compinit -i
autoload -U +X bashcompinit && bashcompinit -i

# Include OS Specific configs
if [[ "${OSTYPE}" == darwin* ]]; then
    [[ -f "$HOME/.maczshrc" ]] && source "$HOME/.maczshrc"
elif [[ "${OSTYPE}" == linux* ]]; then
    [[ -f "$HOME/.linuxzshrc" ]] && source "$HOME/.linuxzshrc"
fi

# golang
# Goenv
# if [ $commands[goenv] ]; then eval "$(goenv init -)"; fi
export GOPATH=$HOME/gopaths/global

[[ -s "$HOME/.gvm/scripts/gvm" ]] && source "$HOME/.gvm/scripts/gvm"

# Rust Lang
export PATH="$HOME/.cargo/env:$PATH"

# jEnv
if [[ -s "$HOME/.jenv/version" ]]; then
    export PATH="$HOME/.jenv/bin:$PATH"
    eval "$(jenv init -)"
    export JAVA_HOME="$(jenv javahome)"
fi

# rvm
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"

# pyenv
if [ $commands[pyenv] ]; then
    export PYENV_ROOT="$HOME/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init --path)"
    eval "$(pyenv init -)";
    eval "$(pyenv virtualenv-init -)"
fi

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion

# pyenv virtual environment wrapper
if which pyenv-virtualenv-init >/dev/null; then eval "$(pyenv virtualenv-init -)"; fi

# direnv
if [ $commands[direnv] ]; then eval "$(direnv hook zsh)"; fi

# K8
if [ $commands[kubectl] ]; then source <(kubectl completion zsh); fi

# Travis CI
[ -f $HOME/.travis/travis.sh ] && source $HOME/.travis/travis.sh

# Added by OrbStack: command-line tools and integration
# Comment this line if you don't want it to be added again.
[ -f $HOME/.orbstack/shell/init.zsh ] && source ~/.orbstack/shell/init.zsh 2 >/dev/null

# A command-line fuzzy finder
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_OPTS="--height 40% --layout=reverse --border --bind 'ctrl-/:toggle-preview'"

# Use fd (https://github.com/sharkdp/fd) instead of the default find
_fzf_compgen_path() {
    fd --hidden --follow --exclude ".git" . "$1"
}

# Use fd to generate the list for directory completion
_fzf_compgen_dir() {
    fd --type d --hidden --follow --exclude ".git" . "$1"
}

# Dummy Secrets
# export AWS_SECRET_ACCESS_KEY=ffasdfasdf1312312341231231
# export OPENAI_KEYS=fasdfl;ksdjfasdfsdfjaksdjfl12asdfj23lasdkf
